issuer: https://token.actions.githubusercontent.com
subject: repo:itv-test/tf-gcp-module-template:ref:refs/heads/main
claim_pattern:
  workflow_ref: itv-test/tf-gcp-module-template/.github/workflows/create-repo.yml@refs/heads/main

permissions:
  administration: write
  repository_custom_properties: write
  contents: write
  workflows: write
